#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@pushbot[-1]
	add ucitrack pushbot
	set ucitrack.@pushbot[-1].init=pushbot
	commit ucitrack
  delete pushbot.pushbot.bark_encryption_iv
  commit pushbot
EOF

rm -rf /tmp/luci-*
exit 0
